### ISSUE TITLE
Docker installation creates unsecured postgreSQL instance

### ISSUE THREAD

**Issue by GKFX** [CHTJonas/roombooking#85]
Will email you re: this. Also I was surprised that the Docker container was coming back up automatically when I rebooted my laptop.

**Comment by CHTJonas** [comment]
Wow thanks for catching this, and all hail the UIS Friendly Probing Service! Pretty sure that surprising behavior is because `docker-compose.yml` has `restart: always` in it, although I have no idea why I wrote that...

Beyond development email addresses there _shouldn't_ be any sensitive/personal data in the database as Camdram OAuth2 tokens belonging to users have been encrypted since db55ecea2fa10c29fdf70904862aefc15deb2a14 and other sensitive data is stored in `ENV` variables. That being said, I'll look at setting a hard-wired Postgres password for the container to be extra safe. Ditto Redis.

**Comment by CHTJonas** [comment]
PR is up! 🎉 

If you haven't already then you should be able to get a totally clean Room Booking slate via the following method:

- `docker ps --all`
- `docker rm -f $ANY_RELEVANT_CONTAINER_ID_FROM_ABOVE`
- `docker volume prune`
- `docker images`
- `docker rmi -f $ANY_RELEVANT_IMAGE_ID_FROM_ABOVE`
